class DHCP2RAD:
    def __init__(self, line: str, *args: list, **kwargs: dict) -> None: ...
    def get_sql_values(self, *args: list, **kwargs: dict) -> str: ...
    def _get_time(self, *args: list, **kwargs: dict) -> str: ...
    def _get_mac(self, *args: list, **kwargs: dict) -> str: ...
    def _get_ip(self, *args: list, **kwargs: dict) -> str: ...
    def __str__(self, *args: list, **kwargs: dict) -> str: ...
