from typing import Any, Union
from .DHCP import DHCP

class MainLog:
    def __init__(self, line: str, *args: list, **kwargs: dict) -> None: ...
    def _add_dhcp_instance(
        self,
        instance: DHCP,
        with_time_delta: bool,
        *args: list,
        **kwargs: dict,
    ) -> None: ...
    def __add__(self, value: Union[str, DHCP], *args: list, **kwargs: dict) -> None: ...
    def get_sql_value(self, *args: list, **kwargs: dict) -> str: ...
    def _get_context(self, *args: list, **kwargs: dict) -> str: ...
    def _get_error(self, *args: list, **kwargs: dict) -> str: ...
    def _get_time(self, *args: list, **kwargs: dict) -> str: ...
    def _get_ip(self, *args: list, **kwargs: dict) -> str: ...
    def __str__(self, *args: list, **kwargs: dict) -> str: ...
